= AWKDoc

Wanted to learn AWK for some time.
This feels like a good project for that.


== Recognition
Obvious inspiration, and some outright function theft, from https://github.com/reconquest/shdoc[shdoc].

There were a few edge cases I didn't love, largely surrounding handling leading whitespace.

Doubt I'll ever reach the quality of `shdoc` (including impressive testing suite).
Though trying my own version, and with different approach.


== Hopeful additions
=== Typedefs
Rather than a freeform type hint, should support declaring locations where a type is defined in code.

[source,bash]
----
# @typedef SOMETHING
declare -a SOMETHING
----

May feel a little repetitive, except it's also useful for dynamic declarations.

[source,bash]
----
# @typedef SOMETHING
declare -a "$VAR"=
----

=== Location information
Should tag each type & function with filename & line number.


=== Expanded multiline support
Ideally everything should allow for multiline descriptions.


== Thinkies
=== Output
How should generated output look.

[source,html]
----
<html>
<body>

<!-- Table of Contents -->
<div>
</div>

<!-- Function documentation -->
<div>
<h1> Section __ </h1>
   <h3> foo() </h3>
   <table>
      <!-- @arg -->
   </table>
   <p>
      <!-- @does -->
   </p>

   <h3> bar() </h3>
   <!-- etc. -->

<h1> Section __ </h1>
<!-- etc. -->
</div>

</body>
</html>
----

Hmm.

As I think more about this, maybe it honestly makes more sense to target asciidoc as the output.
You can compile asciidoc to HTML.
Allows more expressiveness.

OoooooooooOoooOOOOOh.

What about targetting a man page format?
I now like this much better.
